name: virotour
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.5
  webviewx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0
  build_runner: '>=1.6.2 <3.0.0'
  build_web_compilers: '>=2.12.0 <4.0.0'

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/images/screenshots
